### ISSUE TITLE
Add a Slack command that lets the user append a project idea to projects.md

### ISSUE THREAD

**Issue by DigTK** [devanooga/devanoobot#7]
It should also add who executed it, so that we can trace it in case someone abuses the command.

**Comment by agarzola** [comment]
I’m working on tests for this feature, so we can start implementation this Wednesday. It sounds like we need to test the following:

1. A `/project` command (or similar).
1. The command should accept a string. _Do we want any validation on it?_
1. Bot receives the request and responds with OK.
1. Bot checks out the latest master, creates a feature branch (probably using a timestamp in the name to avoid collisions).
1. Bot appends the string to the bottom of the `devanooga-meta/hack-night/projects.md` file (with the submitting user’s handle and full name, if available).
1. Bot commits that change and pushes to the `devanooga-meta` repo.
1. Bot submits pull request.
1. Bot posts a link to the PR in #hacknight.

Am I missing anything here?

**Comment by DigTK** [comment]
Looks good to me

I don't think we need any string validation because all a malicious string would manage to do is get into a PR, which we can then just trash if we don't like it.

**Comment by agarzola** [comment]
I think it should be sanitized.

**Comment by agarzola** [comment]
We might end up doing some of this via shell script, so the potential for fuckery is actually quite high.

**Comment by agarzola** [comment]
Implemented in #9.
